<?php

namespace Whatsup\SUPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenueRepository extends EntityRepository
{
	public function findEventsWithinDateRange($id, $start, $end){
		$events = array();
		$venue = $this->find($id);
		foreach($venue->getEvents() as $event){
			if($event->getStartdate()->getTimestamp() >= $start && $event->getStartdate()->getTimestamp() <= $end){
				$myEvent = array(
					"id" => $event->getId(), 
					'title' => $event->getName(),
					'start' => $event->getStartdate()->format('Y,m,d'),
					'end' => $event->getEnddate()->format('Y,m,d'),
					'url' => "/event/" . $event->getId() . "/show",
				);
				$events[] = $myEvent;
			}
		}		
		return $events;
	}
}